### ISSUE TITLE
print_trainable_parameters(model) gives different number from foundational pertained model

### ISSUE THREAD

**Issue by tom192180** [huggingface/peft#1020]
### System Info

I was reading your official tutorial, and I found it used 20b.
But it only printed 10b in your tutorial. Why is this the case?

trainable params: 8650752 || all params: 10597552128 || trainable%: 0.08162971878329976

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

https://colab.research.google.com/drive/1VoYNfYDKcKRQRor98Zbf2-9VQTtGJ24k?usp=sharing#scrollTo=Ybeyl20n3dYH

### Expected behavior

trainable params: 8650752 || all params: 20b  || trainable%: 0.08162971878329976

**Comment by SumanthRH** [comment]
Hi! Not a maintainer but I can answer this. The bnb_4bit_training.ipynb notebook you shared is dated! With 4bit quantization, there is indeed a correction factor of 2 needed for the number of trainable parameters to be right. This was already fixed in https://github.com/huggingface/peft/pull/733, and you can use `model.print_trainable_parameters()` to get the correct number now (instead of the utility function in the notebook). Hope that helps.
