### ISSUE TITLE
I want to use PEFT to load the Lora model and keep the original model

### ISSUE THREAD

**Issue by LDLINGLINGLING** [huggingface/peft#1161]
### System Info

peft ,transformer

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

```python
    max_memory = f"{int(torch.cuda.mem_get_info()[0] / 1024 ** 3) - 2}GB"
    generation_config = GenerationConfig.from_pretrained(base_path, trust_remote_code=True)
    model = AutoModelForCausalLM.from_pretrained(
            base_path,
            device_map="cuda:0",
            max_memory=max_memory,
            trust_remote_code=True,
            #use_safetensors=True,
            bf16=True
        ).eval()
    merge_model = PeftModel.from_pretrained(model, adapter_path)
    merge_model.generation_config.eos_token_id=[2512,19357,151643]
```

### Expected behavior

I want the model and merge_model in the code will have diffrent output: the model will give me a output of the base model,the merge_model will give me a output of the finetune lora model.

**Comment by BenjaminBossan** [comment]
This is not really possible because PEFT will modify the `model` inplace. If you want to have both at the same time, you need to either load the `model` again, or create a `deepcopy` before passing it to `PeftModel.from_pretrained`.

Note, however, that using the `merge_model`, you can still get inference/generations of the base model, e.g. by calling:

```python
with merge_model.disable_adapter():
    outputs = merge_model(**inputs)
```

This gives you the same output as the `model`.
