### ISSUE TITLE
LoRA applied to encoder and decoder block of a seq-to-seq model

### ISSUE THREAD

**Issue by BSharmi** [huggingface/peft#1184]
### Feature request

Hi there!
Is it possible to take the encoder and decoder block of a seq-to-seq model like T5 and apply LoRA to each module instead of loading an ` AutoModelForSeq2SeqLM` directly?

### Motivation

If we want to have a conditional T5 model where I want to have a conditional module in between encoder and decoder and mix the encoder last hidden state with the conditional module before passing to the decoder, I want to load the encoder and decoder separately. 

### Your contribution

I was thinking of loading the full model and splitting as below
```
MODEL_NAME = "google/flan-t5-small"
T5model = T5Model.from_pretrained(MODEL_NAME)
enc_model = T5model.encoder
dec_model = T5model.decoder
```
Can I then apply LoRA with `FEATURE_EXTRACTION` task for encoder and `CAUSAL_LM` task for the decoder?

**Comment by BenjaminBossan** [comment]
In principle, this should be possible. You could call `get_peft_model` on `encoder` and `decoder` separately, which will result in the PEFT adapters being injected into them inplace. You could also use `peft.inject_adapter_into_model` to directly inject the adapters into `encoder` and `decoder`.

A possible issue with this approach is that you will only have the inplace-modified modules, not a `PeftModel` instance. This means that you'll lose some of the comfort features that `PeftModel` provides, e.g. the ability to save and load only the additional adapter weights instead of the whole model, merging of adapter layers etc. If you can live without those features, I think your suggested approach should work.

**Comment by BSharmi** [comment]
Thank you. Good point about the missing benefits in this approach, I will dig deeper.
