### ISSUE TITLE
[Documentation] Request to Include LoftQ and LQ-LoRA

### ISSUE THREAD

**Issue by HanGuo97** [huggingface/peft#1404]
Hi,

Firstly, thanks for making this amazing library -- it's an invaluable resource for the community!

Recently, we noticed the addition of LoftQ to the library – a fantastic development! We believe it's worth mentioning that [LQ-LoRA](https://arxiv.org/abs/2311.12023), which shares similar ideas and is also based on the `peft` library, parallels LoftQ's efforts. Though it isn't directly integrated with `peft`, we feel it complements the current documentation ([here](https://huggingface.co/docs/peft/developer_guides/quantization#loftq-initialization) and [here](https://huggingface.co/docs/peft/main/en/developer_guides/lora#loftq)). It'd be great if the documentation pages could be updated to mention this work, and I'm happy to contribute if it's helpful.

Thanks in advance for your help!

**Comment by BenjaminBossan** [comment]
Thanks for the suggestion. Indeed, LQ-LoRA could be very interesting to many PEFT users. As such, I wouldn't be opposed to add a reference to it.

Looking at the [github repo](https://github.com/HanGuo97/lq-lora), one major issue I see is that installation is not very straightforward. Do you plan to add a pypi package for the repo? Otherwise, I would imagine that most users will not go through the moves to install your package.

If you're interested in this, I think what would be even better is to directly integrate LQ-LoRA into PEFT, similar to how LoftQ was integrated. Is this something you would be interested in collaborating in? We would definitely support you from the PEFT side to get this working.

**Comment by HanGuo97** [comment]
Thanks for the response -- we'd love to contribute!

I agree the current interface isn't the most accessible. We are working on an extension to the project (and plan to wrap it up in ~a month or so). How about I get back to you regarding integration after this?

In the meantime, I was thinking about adding a few sentences/references to LQ-LoRA (e.g., when discussing LoftQ because of the similarity, but I'm fine wherever you think fits better).

Thanks again!

**Comment by BenjaminBossan** [comment]
> How about I get back to you regarding integration after this?

Yes, that sounds great.

> I was thinking about adding a few sentences/references to LQ-LoRA (e.g., when discussing LoftQ because of the similarity, but I'm fine wherever you think fits better).

I think that would make sense once there is a pypi package, and with the addition of a small code snippet that shows the usage. Otherwise, from my experience, the vast majority of users won't even try.

**Comment by HanGuo97** [comment]
Understand, thanks again for being super helpful!

**Comment by BenjaminBossan** [comment]
We can leave this issue open as a reminder if you like, up to you.
