### ISSUE TITLE
Running multiple adapters simultaneously, reusing the output from the base model

### ISSUE THREAD

**Issue by sachin-patel-qp** [huggingface/peft#1434]
I'm new to the concept of adapters and had a question: Is it possible to run multiple adapters simultaneously while reusing the output from the base model?

For instance, consider a base model named Base_model and 2 adapters, Adapter_1 and Adapter_2. 
Currently, to obtain outputs from these two different adapters, we need to load and run them separately:

1. Base_model --> Adapter_1 ---> Output_1
2. Base_model --> Adapter_2 ---> Output_2

My question is, can we somehow reuse or save the output from the Base_model and pass it to different adapters as needed?

1. Base_model --> **Base_output** (Save this) & use to give input to adapter
2. **Base_output** --> Adapter_1 ---> Output_1
3. **Base_output** --> Adapter_2 ---> Output_2

**Comment by BenjaminBossan** [comment]
Hi, IIUC, what you want is to get the base output from the base model, then apply the adapter 1 and adapter 2 (separately) on top of the base output. The idea would be to save on computation by only having to compute the base output once, instead of twice as in the first example. This would basically be a form of caching. Please let me know if I got this correctly.

In general, this approach will not work. You don't specify the type of adapter, but let's go with LoRA. The output for the LoRA adapter is not simply the output from the base model + some LoRA output on top. Although this is the case for a single layer, it is not true for the whole net. Since the LoRA adapter changes the output for the first layer, the input to the second layer is already different. Therefore, the base output for the second layer already diverges, and the "cached" output is of no use. Does that make sense?

Do note, however, that it is possible to load the base model with multiple adapters at the same time. Maybe you already know this, but if not, this allows you to at least save some memory by not having to load the base model twice.

**Comment by BenjaminBossan** [comment]
Sorry, I don't think this would work with any of the PEFT methods we have, simply because they will modify the activations early on in the network graph, thus influencing all downstream activations, making caching impossible.

What could work for you classification use case is a "traditional" approach of freezing all weights except for the classification head, then training 2 different classification heads for your tasks. Then you can compute the activations right up until the classification heads and cache those. The downside is that this type of fine-tuning will most likely not match the performance of LoRA etc.

**Comment by dongxiaolong** [comment]
> Yes I want to save computation by computing base output once (caching) To give an example let's say 2 adapters that classify text: Adapter_1 for Sentiment & Adapter_2 for Emotions
> 
> As per your explanation, the base model doesn't generate a shared output for adapters. Instead, it is adapter-dependent, modifying the base model's output from the first layer itself.
> 
> @BenjaminBossan Are there alternative approaches to achieve the goal of caching?

I think you can use [S-LoRa]( https://github.com/S-LoRA/S-LoRA). It's close to your scenario, but can't use your ideas.
