### ISSUE TITLE
Add a new fine-tuning method called Conv-Lora

### ISSUE THREAD

**Issue by 2catycm** [huggingface/peft#1560]
### Feature request

1. link to the source.
This is an ICLR 2024 paper, titiled "Convolution Meets LoRA: Parameter Efficient Finetuning for Segment Anything Model". 
Here is the openreview link: 
https://openreview.net/forum?id=ezscMer8L0

### Motivation

2. evidence there is general interest in using the method
- The paper did extensive experiments, demonstrating its power in finetuning SAM. 
- This method inject the locality inductive bias by using convolution, so it might generally enhance the peft performance in image related tasks. 
- This method uses MoE to model different scale, which is interesting.  
- SAM's image encoder is a plain ViT, so performance gain on SAM is also expected in other ViT. 
- Another popular ML library called AutoGluon is also introducing this method into their repository

### Your contribution

Trying to implement it. 
This method seems similar to LoRA, it makes sense to structure the code similarly or even reuse some functions or classes where it makes sense.

**Comment by BenjaminBossan** [comment]
Thanks for bringing this method to our attention. If you want to work on it, feel free to open a draft PR so that we can give feedback early.

From a quick glance at the paper, this looks indeed very similar to LoRA with an extra step between the A and B weights. However, the results also look very similar to LoRA, with only a slight improvement on most tests. I couldn't spot anything on runtime performance of this new method and whether it can be merged into the base weights, both of which are important considerations for LoRA. If you have a real world problem you try to solve, I'd definitely give LoRA a try first.
