### ISSUE TITLE
p_tuning layers disappear after loading peft model

### ISSUE THREAD

**Issue by victoriousMan** [huggingface/peft#1607]
After I trained my peft model  (in this case P_Tuning), I save it using save_pretrained method. Later I load the model using:
```
config.peft_config = PeftConfig.from_pretrained(peft_model_id,
                                            inference_mode=inference)
MODEL_TASK_TYPE = {
    TaskType.CAUSAL_LM: AutoModelForCausalLM,
    TaskType.SEQ_2_SEQ_LM: AutoModelForSeq2SeqLM,
    TaskType.SEQ_CLS: AutoModelForSequenceClassification,
}
base_model = MODEL_TASK_TYPE[self.task_type].from_pretrained(config.peft_config.base_model_name_or_path)
self.model = PeftModel.from_pretrained(base_model, config.prompt_model_name_or_path) # prompt_model_name_or_path is the dir where I save my peft model
```
When I query `self.model.prompt_encoder` I only see the embedding layer of the prompt. How can I load the model with all layers of the prompt as was during training?

This question brings another question. How does inference work? I tried tracing the function calls after `model(**input)` and noticed that the embeddings of the prompt (which are randomly initialized) is concatenated to the input, and the whole thing is embedded by the word embedding layer of the base model and sent to the base model forward function. I am not sure how the trained p_tuning layers are used during inference.

**Comment by BenjaminBossan** [comment]
> When I query `self.model.prompt_encoder` I only see the embedding layer of the prompt. How can I load the model with all layers of the prompt as was during training?

Indeed, currently, when we save the p-tuning model, the MLP part (which I think is what you're referring to) is not being saved along with the prompt embedding. My guess is that when this code was written, it was assumed that after initial training, there is no further training step, which makes it unnecessary to load the whole `p_tuning.PromptEncoder` module. Pinging @pacman100 if he can confirm this.

Do you plan to do further training? If not, then you shouldn't need the additional layers.

**Comment by BenjaminBossan** [comment]
> Yes, I plan to do further training.

While waiting for a reply, note that you can always use `torch.save` and `torch.load` to save and load the whole model the normal PyTorch way. This isn't super nice because the resulting file will be much larger than only the PEFT adapter, but if that's not a limitation for you, you could give it a try.

> Also, I just noticed that the classifier layer is tuned, which I am not sure if it should be according to p_tuning paper.

Note that we generally want the methods we implement to be widely applicable, and not to work only for the tasks mentioned in the paper. If you want to apply p-tuning to a sequence classification task (if that's what you mean), a new classification head has to be added and it needs training for it to work properly.

**Comment by victoriousMan** [comment]
It's clear to me know. Thank you @BenjaminBossan  for your prompt response.
