### ISSUE TITLE
Backward compatibility on saved config.

### ISSUE THREAD

**Issue by xkszltl** [huggingface/peft#1650]
### Feature request

Model trained on newer peft should be available on older version when possible.

### Motivation

We found model trained on peft 0.10 cannot be loaded with older peft due to unknown entry `layer_replication` in adapter config json.
This entry is never used by us so it's probably just the default value.
Default value like this should not be exported.

### Your contribution

N/A

**Comment by BenjaminBossan** [comment]
What you are asking is not backwards compatibility, but forward compatibility. The case you describe is backwards compatible.

Removing defaults is not always a good idea, because it means we cannot change the defaults in the future if we find it necessary. Being explicit is better here.

For your use case, you can just manually delete the attributes you don't need and it should work.

**Comment by xkszltl** [comment]
It is backward compatibility on the model file schema. 
New version of runtime should avoid breaking change to the resulting model.

And regarding changing default in the future, it’s better for future version to worry about that as part of its compatibility.
IMO it’s simply a bad idea to change implicit default without introducing a new API because that’s a breaking change.
If there’s a need for variable default, be explicit, have something like “auto” for user to enroll into that rolling behavior, or have a util func to generate the default value of that version.
