### ISSUE TITLE
Whisper PEFT int8 - peft adapters ?¿

### ISSUE THREAD

**Issue by javilonso** [huggingface/peft#174]
Hi @pacman100 , another question for you!

In the [example notebook ](https://github.com/huggingface/peft/blob/main/examples/int8_training/peft_bnb_whisper_large_v2_training.ipynb), there is a warning when calling **Seq2SeqTrainer**.

```
The model is loaded in 8-bit precision. To train this model you need to add additional modules inside the model such as **adapters** using `peft` library and freeze the model weights. Please check  the examples in https://github.com/huggingface/peft for more details.
```

I don't really understand what those "adapters" are, do yo? Are they necessary? Because you did not add them.

----

Another question not related with my previous message. 
Peft + int8 reduces the amount of GPU memory needed to train. 
Do this changes add any other improvement? Training time reduced? Inference time reduced?

Thanks again! I hope this questions also help other people understand peft :)

**Comment by pacman100** [comment]
Hello @javilonso ,

>  don't really understand what those "adapters" are, do yo? Are they necessary? Because you did not add them.

"adapters" in general mean peft methods such as LoRA, prefix-tuning. It was one of the first papers to introduce parameter-efficient fine-tuning and that terminology became popular. You can safely ignore the warning.

> Peft + int8 reduces the amount of GPU memory needed to train.
Do this changes add any other improvement? Training time reduced? Inference time reduced?

1. As the amount of GPU memory required is reduced, you can fit larger batches leading to faster training thereby reducing training time
2. Inference time should be same.
3. Another major benefit is tiny checkpoints reducing storage costs significantly, these can be easily shared, best example is dreambooth wherein users want to fine-tuning it on many downstream datasets, the resulting checkpoints for each such dataset will be in MBs instead of 10s of GBs. Same goes for whsiper fine-tuning on downstream languages.

**Comment by javilonso** [comment]
> Hello @javilonso ,
> 
> > don't really understand what those "adapters" are, do yo? Are they necessary? Because you did not add them.
> 
> "adapters" in general mean peft methods such as LoRA, prefix-tuning. It was one of the first papers to introduce parameter-efficient fine-tuning and that terminology became popular. You can safely ignore the warning.
> 
> > Peft + int8 reduces the amount of GPU memory needed to train.
> > Do this changes add any other improvement? Training time reduced? Inference time reduced?
> 
>     1. As the amount of GPU memory required is reduced, you can fit larger batches leading to faster training thereby reducing training time
> 
>     2. Inference time should be same.
> 
>     3. Another major benefit is tiny checkpoints reducing storage costs significantly, these can be easily shared, best example is dreambooth wherein users want to fine-tuning it on many downstream datasets, the resulting checkpoints for each such dataset will be in MBs instead of 10s of GBs. Same goes for whsiper fine-tuning on downstream languages.

Thanks for such a great answer! Everything understood, tks again!

**Comment by pacman100** [comment]
Unable to reproduce the issue when not using the int8 quantization
<img width="1258" alt="Screenshot 2023-03-30 at 8 16 45 PM" src="https://user-images.githubusercontent.com/13534540/229026654-16415418-9355-4e38-b518-7079fd7dae0e.png">
<img width="1158" alt="Screenshot 2023-03-30 at 8 18 42 PM" src="https://user-images.githubusercontent.com/13534540/229026665-0983e09a-26a4-4f8c-86f7-91595f7ac25e.png">
<img width="938" alt="Screenshot 2023-03-31 at 10 08 15 AM" src="https://user-images.githubusercontent.com/13534540/229026668-347061bc-a93f-4907-9fb8-791ae0e76042.png">

**Comment by javilonso** [comment]
In that case, this issue comes from the dataset (can't share it). Tks for checking @pacman100 !
