### ISSUE TITLE
A bug caused by `endswith` when using modules_to_save.

### ISSUE THREAD

**Issue by gary-young** [huggingface/peft#1917]
### System Info

I find in the line 326 in the file `peft/src/peft/utils/other.py`, where the modules_to_save modules should be set trainable and here a `endswith` is used to determine whether a modules has been listed in the modules to save. However, I find a very special case that if  there are two modules with the same end string but only one of them is listed in the modules_to_save. The `endswith` cannot correct distinct them. For example, in my code, there are two modules with name "model.layers.0.xxxx" and another with name "img_model.layers.0.xxxx", and it cause a bug that the latter was also mistakenly set to trainable.

I don't know why the `endswith` will be used here. But I think it is common to coincidentally have two modules with the same ending.

### Who can help?

@BenjaminBossan 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

A model with two different modules with the same ending string. Only one of them is in the modules_to_save.

### Expected behavior

Only the one in the modules_to_save should be set as trainable.

**Comment by BenjaminBossan** [comment]
If you set `modules_to_save=["model.layers.0.xxxx"]`, would that solve your problem?

**Comment by gary-young** [comment]
@BenjaminBossan No, in fact I indeed set `modules_to_save=["model.layers.0.xxxx"]` when I meet this bug. However, because there is another modules named img_model.layers.0.xxxx. It could be also matched by the `endswith`.

I solve my problem by changing the latter name as `model_img` instead of `img_model`. However, I believe it is a subtle bug that may lead to unexpected behavior. At the very least, users should be warned of this.

**Comment by BenjaminBossan** [comment]
Thanks for clarifying, I see now what the issue is. The problem is that we cannot easily change this, because we cannot know the intent of the user. Maybe they really want to match both `model.layers.0.xxxx` and `img_model.layers.0.xxxx`. If we change how this works, as existing code could break.

After some digging, I think it would be possible to allow passing strings to `modules_to_save`, which we could match with regex. That way, users could pass `modules_to_save="^bar"` in order to match `bar` but not `foobar`. This should be backwards compatible.

However, this would be a bigger refactor, which I currently don't have time to work on. I'll put in on the backlog though. For the time being, the solution you suggested is the only one that works.
