### ISSUE TITLE
 Applying Dora to o_proj of Meta-Llama-3.1-8B results in NaN

### ISSUE THREAD

**Issue by zwhe99** [huggingface/peft#2049]
### System Info

transformers==4.43.3
peft==0.11.2
accelerate==0.33.0

### Who can help?

@BenjaminBossan @ariG23498 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

As the title says, I encountered NaN values when fine-tuning Llama-3.1-8B using Dora. 

After some debugging, I found that the o_proj layer has a lot of zero values in the weight matrix, resulting in zero weight_norm. This will further result in a divide by zero error in the [forward pass](https://github.com/huggingface/peft/blob/37b9c5c74b114d8ab25a9e5430621e0752b8fbcb/src/peft/tuners/lora/dora.py#L88).

Maybe we should assign a small value to zero elements in the weight_norm? Or any other suggestions?

Reproduction:

* Add the following code snippet to the [get_weight_norm](https://github.com/huggingface/peft/blob/37b9c5c74b114d8ab25a9e5430621e0752b8fbcb/src/peft/tuners/lora/dora.py#L30) function:
```python
    def get_weight_norm(self, weight, lora_weight, scaling) -> torch.Tensor:
        # calculate L2 norm of weight matrix, column-wise
        weight = transpose(weight, self.fan_in_fan_out)
        weight = weight + scaling * lora_weight
        weight_norm = torch.linalg.norm(weight, dim=1).to(weight.dtype)

        # >>> debug
        if (weight_norm == 0).any():
            zero_indices = weight_norm == 0
            zero_count = zero_indices.sum()

            print(f"zero_count: {zero_count}")
            print(f"weight[zero_indices]: {weight[zero_indices]}")
            print(f"norm of weight[zero_indices]: {torch.linalg.norm(weight[zero_indices], dim=1)}")
            raise ValueError(f"zero found in weight_norm:")
        # <<< debug

        return weight_norm
``` 

* Run
```python
from transformers import AutoModelForCausalLM
from peft import LoraConfig, get_peft_model

model = AutoModelForCausalLM.from_pretrained("meta-llama/Meta-Llama-3.1-8B")
peft_config = LoraConfig(target_modules=["o_proj"], use_dora=True)
model = get_peft_model(model, peft_config)
```
* Output
```
[root@ts-067ef54ed11a4ec1aef3d7b34368f111-launcher W2S]# python3 /xxx/mini.py
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:22<00:00,  5.68s/it]
zero_count: 511
weight[zero_indices]: tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], grad_fn=<IndexBackward0>)
norm of weight[zero_indices]: tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.], grad_fn=<LinalgVectorNormBackward0>)
Traceback (most recent call last):
  File "/xxx/mini.py", line 6, in <module>
    model = get_peft_model(model, peft_config)
  File "/xxx/peft/src/peft/mapping.py", line 182, in get_peft_model
    return PeftModel(model, peft_config, adapter_name=adapter_name, autocast_adapter_dtype=autocast_adapter_dtype)
  File "/xxx/peft/src/peft/peft_model.py", line 156, in __init__
    self.base_model = cls(model, {adapter_name: peft_config}, adapter_name)
  File "/xxx/peft/src/peft/tuners/lora/model.py", line 139, in __init__
    super().__init__(model, config, adapter_name)
  File "/xxx/peft/src/peft/tuners/tuners_utils.py", line 166, in __init__
    self.inject_adapter(self.model, adapter_name)
  File "/xxx/peft/src/peft/tuners/tuners_utils.py", line 412, in inject_adapter
    self._create_and_replace(peft_config, adapter_name, target, target_name, parent, current_key=key)
  File "/xxx/peft/src/peft/tuners/lora/model.py", line 230, in _create_and_replace
    new_module = self._create_new_module(lora_config, adapter_name, target, **kwargs)
  File "/xxx/peft/src/peft/tuners/lora/model.py", line 324, in _create_new_module
    new_module = dispatcher(target, adapter_name, lora_config=lora_config, **kwargs)
  File "/xxx/peft/src/peft/tuners/lora/layer.py", line 1274, in dispatch_default
    new_module = Linear(target, adapter_name, **kwargs)
  File "/xxx/peft/src/peft/tuners/lora/layer.py", line 486, in __init__
    self.update_layer(
  File "/xxx/peft/src/peft/tuners/lora/layer.py", line 153, in update_layer
    self.dora_init(adapter_name)
  File "/xxx/peft/src/peft/tuners/lora/layer.py", line 252, in dora_init
    dora_layer.update_layer(base_layer=self.get_base_layer(), lora_A=lora_A, lora_B=lora_B, scaling=scaling)
  File "/xxx/peft/src/peft/tuners/lora/dora.py", line 71, in update_layer
    weight_norm = self.get_weight_norm(weight, lora_weight, scaling)
  File "/xxx/peft/src/peft/tuners/lora/dora.py", line 44, in get_weight_norm
    raise ValueError(f"zero found in weight_norm:")
ValueError: zero found in weight_norm:
```

### Expected behavior

Do not trigger the ValueError

**Comment by BenjaminBossan** [comment]
Thanks for reporting.

Indeed, the weight norm could indeed contain zeros if a whole column of the targeted weight only contains zeros. However, I'm not sure why that is happening to you. I checked `"meta-llama/Meta-Llama-3.1-8B"` and there is not a single zero value in any of the `o_proj` layers (not to mention whole columns being zero):

```python
>>> model = AutoModelForCausalLM.from_pretrained("meta-llama/Meta-Llama-3.1-8B")
>>> any((model.model.layers[i].self_attn.o_proj.weight == 0).any() for i in range(32))
False
```

I also created a DoRA model targeting `o_proj` and all logits of this model are finite. Do you have any idea why you get different results?

**Comment by zwhe99** [comment]
This is so weird.

<img width="1337" alt="image" src="https://github.com/user-attachments/assets/3470f419-8aa1-4b3c-98ca-6fbd58a4f097">

**Comment by BenjaminBossan** [comment]
Haha, really strange. Can you take the mean to see how many values are zeros for you on average?

I wonder if something could have gone wrong with the download. Maybe you could try deleting the cache for that model and load it again?

**Comment by ariG23498** [comment]
I get non-zero `o_proj` weights. Here is the [colab notebook](https://colab.research.google.com/gist/ariG23498/d6ff2f1a77a47d6fd44c59200e13a803/scratchpad.ipynb) for reproduction. I also suspect an error with download and think a fresh weight download would mitigate the issue.

**Comment by zwhe99** [comment]
Yes. Re-downloading solved the problem. Thanks! 
<img width="572" alt="image" src="https://github.com/user-attachments/assets/0d63b15a-1d10-421e-b5de-04aa89a160da">

**Comment by zwhe99** [comment]
Sorry for coming back again. Can you help to see if your model has 0 in `gate_proj`.

**Comment by ariG23498** [comment]
Here is the [GIST](https://colab.research.google.com/gist/ariG23498/4bb5f89e63b08f697e333256758d1d14/scratchpad.ipynb) to show that there is no 0 in `gate_proj`.

**Comment by zwhe99** [comment]
Thanks! After re-downloading I noticed that the zeros in o_proj were no longer there instead appearing in gate_proj. I re-downloaded it again and now it's finally working.

**Comment by BenjaminBossan** [comment]
@zwhe99 Great that it works now. You can check the sha256 sum of your downloaded weights against the values shown on HF Hub, e.g. here for the first file of Llama3.1 8B:

https://huggingface.co/meta-llama/Meta-Llama-3.1-8B/blob/main/model-00001-of-00004.safetensors

This should ensure that they're the same. If it keeps happening to you that the downloads are broken, consider opening an issue on the huggingface_hub library: https://github.com/huggingface/huggingface_hub/issues

**Comment by NvMayMay** [comment]
Hi — confirming this bug is still live in peft `0.19.1` (and on `main` as of this writing), and reproducing it on a different architecture with a concrete diagnostic and a proposed fix.

## Repro on a hybrid SSM/attention MoE

- Base model: a Qwen3.5-MoE hybrid (`model_type = "qwen3_5_moe"`, architecture class `Qwen3_5MoeForConditionalGeneration`), bf16 weights loaded with `trust_remote_code=True`.
- Stack: `torch 2.12.0+cu130`, `transformers 5.8.1`, `peft 0.19.1`, single GPU, `dtype=bfloat16`.
- LoRA targets: `"all-linear"`. With `use_dora=False`, training converges normally. With `use_dora=True`, the very first microbatch returns `loss = NaN`.

## Diagnostic

A one-shot probe loads the base model on CPU in bf16 and computes per-row L2 norms of every `nn.Linear`:

```python
for name, mod in model.named_modules():
    if not isinstance(mod, torch.nn.Linear):
        continue
    fp32_norms = mod.weight.float().norm(dim=1)
    zero_rows  = int((fp32_norms == 0).sum())
    # ...
```

Results (only listing the suffixes with non-trivial near-zero rows; all others are fine):

| layer suffix | total rows across all instances | rows with fp32 norm == 0 | min fp32 norm |
|---|---|---|---|
| `in_proj_qkv` (30 instances, SSM-style mixer) | 245,760 | **434** | 0 |
| `in_proj_a`   (30 instances) | 960 | 0 (but 3 rows < 1e-6, min 4.35e-7) | 4.35e-7 |

The 434 zero-norm rows in `in_proj_qkv` are concentrated in the earliest layers (`layer.0`: 112 rows, `layer.1`: 198 rows, `layer.2`: 112 rows, with a handful in `layer.9/10/21/22`). These are genuinely zero in storage, not bf16 underflow. (FWIW, an Ollama report — [ollama/ollama#15866](https://github.com/ollama/ollama/issues/15866) — independently noted that these specific early-layer K rows in the same checkpoint family are small enough that NVFP4 quantization rounded them to zero.)

## Where the NaN comes from

In [`peft/tuners/lora/dora.py`](https://github.com/huggingface/peft/blob/main/src/peft/tuners/lora/dora.py), `DoraLinearLayer.get_weight_norm` computes:

```python
weight = weight + scaling * lora_weight
weight_norm = torch.linalg.norm(weight, dim=1).to(weight.dtype)
return weight_norm
```

For rows where the base weight is exactly zero (and `lora_weight ≈ 0` at adapter init, since LoRA-B is zero-initialized), `weight_norm` is 0. Then in `forward`:

```python
mag_norm_scale = (magnitude / weight_norm).view(1, -1)
```

`magnitude / 0` produces `inf` (or NaN if magnitude is also 0, which it is at init since it was set to the same `weight_norm`). That `inf` propagates through `(mag_norm_scale - 1) * base_result + mag_norm_scale * lora_result * scaling` and pollutes the loss as NaN on the first microbatch. This is exactly the same code path as in the original report — the o_proj rows reported here had the same property.

## Proposed fix

Two changes to `DoraLinearLayer.get_weight_norm` (and `_DoraConvNdLayer.get_weight_norm`):

1. Upcast `(weight + scaling * lora_weight)` to fp32 before the norm — handles bf16/fp16 underflow cases where the row isn't literally zero but rounds to zero in low precision.
2. Clamp the resulting norm at `eps = 1e-6` before returning — handles the genuinely-zero-row case (any architecture with sparsified/pruned/zero-initialized projection rows).

Both follow established prior art: `eps = 1e-6` for bf16/fp16 is the value recommended in "Scaling DoRA" ([arxiv 2603.22276](https://arxiv.org/abs/2603.22276)), and `torchtune`'s DoRA accumulates the norm in fp32 under `torch.no_grad`. Together they make DoRA architecture-agnostic for any target module that may contain near-zero rows.

A minimal patch (against `main`):

```diff
-    @cache_decorator("weight-norm")
-    def get_weight_norm(self, weight, lora_weight, scaling, adapter_name: Optional[str] = None) -> torch.Tensor:
-        # calculate L2 norm of weight matrix, column-wise
-        weight = transpose(weight, self.fan_in_fan_out)
-        weight = weight + scaling * lora_weight
-        weight_norm = torch.linalg.norm(weight, dim=1).to(weight.dtype)
-        return weight_norm
+    @cache_decorator("weight-norm")
+    def get_weight_norm(self, weight, lora_weight, scaling, adapter_name: Optional[str] = None) -> torch.Tensor:
+        # Row-wise L2 norm of (base + scaled LoRA). Upcast to fp32 for the norm to avoid bf16/fp16
+        # underflow on near-zero rows, and clamp away from zero so the downstream
+        # ``magnitude / weight_norm`` divide in forward() cannot produce inf/NaN on genuinely zero rows.
+        # See GH issue #2049 and "Scaling DoRA" (arxiv:2603.22276) for the eps=1e-6 convention.
+        target_dtype = weight.dtype
+        weight = transpose(weight, self.fan_in_fan_out)
+        merged = weight.float() + scaling * lora_weight.float()
+        weight_norm = torch.linalg.norm(merged, dim=1)
+        weight_norm = torch.clamp(weight_norm, min=1e-6)
+        return weight_norm.to(target_dtype)
```

The same shape of change applies to `_DoraConvNdLayer.get_weight_norm`.

## Verification

After applying the fix as a monkey-patch in our training script (`peft.tuners.lora.dora.DoraLinearLayer.get_weight_norm = <patched>` before `get_peft_model()`):

| run | config | first microbatch loss | outcome |
|---|---|---|---|
| unpatched peft 0.19.1 | DoRA r=16 α=32 `target_modules="all-linear"` | **NaN** | killed at step 0 |
| same + this patch | DoRA r=16 α=32 `target_modules="all-linear"` | **1.249** (finite) | trained to completion (3 epochs, 66 optimizer updates) with **final val_loss 0.7647**. Plain LoRA at the same r/α/targets and dataset on this model finishes at **0.7635** — DoRA is within 0.2 % and was *below* the LoRA baseline at the intermediate step-50 eval (0.7621). |

Eval trajectory of the patched DoRA run for reference:

| step | val_loss |
|---|---|
| 25 (epoch 1 boundary) | 0.7884 |
| 50 (mid-epoch 3) | 0.7621 |
| 66 (final, after epoch 3) | 0.7647 |

The monkey-patch is identical to the diff above. The training script logs a `monkey_patch_applied` event into the run metrics so the active patch is auditable per run.

Happy to open a PR with the patch + a unit test that constructs a Linear with deliberately zero rows, attaches DoRA, runs one bf16 forward, and asserts no NaN — that test fails in current `main` and passes after the patch. Let me know if you'd like that.
