### ISSUE TITLE
Is it possible to load a model from my local path, like YoloV7.pt in my local?

### ISSUE THREAD

**Issue by MillionaireChen** [huggingface/peft#2057]
### Feature request

After exploring the EXAMPLES directories, I found there is no object detection demo.

I try to change the model id from the hugging face. https://huggingface.co/Yolov7/yolov7

But there is no config files in hugging face website of YOLOV7. But this 

### Motivation

Although PEFT is mainly used for simplified training of large models, I think it should be regarded as a general technique rather than focusing on large models.

### Your contribution

None

**Comment by BenjaminBossan** [comment]
If I understand your question correctly, you want to know if it's possible to apply PEFT techniques to a model loaded locally. Yes, in general you can apply PEFT to any PyTorch model, as long as the layer types are supported (e.g. for LoRA, that would be `Linear`, `Conv2d` and `Embedding` at the moment). More docs on that [here](https://huggingface.co/docs/peft/developer_guides/custom_models).

Your issue seems to be how to load the base model, in your case YOLOv7. This isn't really a PEFT question, as PEFT doesn't care how you load the base model. The repo you linked does not contain any further information. However, [this repo](https://github.com/WongKinYiu/yolov7/) seems to be the official YOLOv7 repo, so check it out to see how to load the model.

**Comment by MillionaireChen** [comment]
Thanks for your prompt and detailed reply. This Huggingface page is what I want. Thanks so much again.
