### ISSUE TITLE
PEFT Config checking update request

### ISSUE THREAD

**Issue by lemingshen** [huggingface/peft#2112]
### Feature request

Position: In peft/tuners/lora/model.py --> LoRaModel._check_new_adapter_config()
The source code suggests a TODO:
![image](https://github.com/user-attachments/assets/b73ef0ef-23d6-42de-a25d-96a4b1d0ef79)

Please complete this checking function ASAP.

### Motivation

When I tried to load multiple LoRA adapters into one base model, a ValueError was raised:
![image](https://github.com/user-attachments/assets/82d8c41d-a9bd-4b25-a215-ed12080fbeef)

After tracing the source code, I found that the adapter config checking function was not completed. So, please complete it.

### Your contribution

NA

**Comment by BenjaminBossan** [comment]
Just to make sure: You are loading multiple LoRA adapters and you have more than one adapter with `bias != "none"`. However, you think the error should not be raised in your case because these LoRA adapters only target modules that don't have a bias. Is that right?

If that's the case, you could edit the `adapter_config.json` to change the `bias` argument to `"none"` and the adapter should load fine.

The reason why I'm asking like this is because adding this check is unfortunately not trivial, which is why there is a TODO there instead of it already being implemented.

**Comment by lemingshen** [comment]
Got it. Thank you so much for the detailed explanations. 👍
