### ISSUE TITLE
a guide to add a new fine-tuning method in the doc

### ISSUE THREAD

**Issue by YF-T** [huggingface/peft#2251]
### Feature request

Hello, I am a researcher in the finetune area. Can you publish a guide to add a new fine-tuning method in the doc? I think researchers like me are glad to experiment their methods based on this repo.

### Motivation

Researchers like me are glad to experiment their methods based on this repo, but don't know how to add.

### Your contribution

Yes, but after verifying the feasibility of my method.

**Comment by BenjaminBossan** [comment]
Thanks for the suggestion. Indeed, it would be great to have a step by step guide on how to add a new fine-tuning method to PEFT. We have a [contribution guideline](https://huggingface.co/docs/peft/developer_guides/contributing#add-a-new-fine-tuning-method) with some paragraphs on adding new methods, not sure if you saw that.

As mentioned, a good way to start is to check previous PRs. Just as an example of a recent PR adding a new method, check out #2172. Also, I typically recommend potential contributes to start with a draft PR that focuses on implementing the new method as a first step. Once this is reviewed, we can work on adding unit tests as a second step. The third step is then to add documentation and examples. Ideally, one of the examples is (similar to) an experiment from the paper, so that we can verify it works as expected.

Let me know if that helps or if you need more details. We can update the contribution guide based on that feedback.

**Comment by YF-T** [comment]
Thank you for your patient reply! I will learn the guide and previous PRs.
