### ISSUE TITLE
How to use PEFT to develop new parameter efficient fine tuning methods

### ISSUE THREAD

**Issue by GeyuanZhang** [huggingface/peft#229]
Can I use PEFT to develop new parameter efficient fine tuning methods? Are there any interface to allow me to do this?

**Comment by pacman100** [comment]
Hello @GeyuanZhang, Thank you for your interest in adding new methods to the repo.  Please find below rough guidelines on how the library is structured, the interfaces to implement and suggestions going forward:
1. Each parameter-efficient fine-tuning method is in a separate file in the tuners folder : [peft/src/peft/tuners at main · huggingface/peft · GitHub](https://github.com/huggingface/peft/tree/main/src/peft/tuners)
2. Main class if PeftModel in [peft/peft_model.py at main · huggingface/peft · GitHub](https://github.com/huggingface/peft/blob/main/src/peft/peft_model.py) with downstream nlp task specific class implementations, e.g., PeftModelForSeq2SeqLM
3. Each tuner has following interfaces, taking [peft/lora.py at main · huggingface/peft · GitHub](https://github.com/huggingface/peft/blob/main/src/peft/tuners/lora.py) as example:
A config extending PeftConfig
A tuner-specific class implementing the PEFT logic for the corresponding method.
4. Currently, only LoRA method modifies the base model in place by injecting additional layers. Prompt learning based methods (Prompt Tuning, P-Tuning and Prefix-Tuning) are not modifying the base models and their logic is coupled to the nlp task-specific classes such as PeftModelForSeq2SeqLM
5. Going forward, all the methods should implement the logic in the way LoRA integration is implemented by injecting/modifying the base model so that it is widely applicable to most of the models and without having to depend on the nlp task-specific classes such as PeftModelForSeq2SeqLM. This has made it quite popular among practitioners.
6. Give proper citations to method, code and implementation utilities
7. Write a few tests and example notebooks to test out the peft method and have it as ready to use artefact for end users. This has particularly helped with the adoption of PEFT.

Follow the LoRA implementation as a reference and develop the new method following it

**Comment by GeyuanZhang** [comment]
> Hello @GeyuanZhang, Thank you for your interest in adding new methods to the repo. Please find below rough guidelines on how the library is structured, the interfaces to implement and suggestions going forward:
> 
> 1. Each parameter-efficient fine-tuning method is in a separate file in the tuners folder : [peft/src/peft/tuners at main · huggingface/peft · GitHub](https://github.com/huggingface/peft/tree/main/src/peft/tuners)
> 2. Main class if PeftModel in [peft/peft_model.py at main · huggingface/peft · GitHub](https://github.com/huggingface/peft/blob/main/src/peft/peft_model.py) with downstream nlp task specific class implementations, e.g., PeftModelForSeq2SeqLM
> 3. Each tuner has following interfaces, taking [peft/lora.py at main · huggingface/peft · GitHub](https://github.com/huggingface/peft/blob/main/src/peft/tuners/lora.py) as example:
>    A config extending PeftConfig
>    A tuner-specific class implementing the PEFT logic for the corresponding method.
> 4. Currently, only LoRA method modifies the base model in place by injecting additional layers. Prompt learning based methods (Prompt Tuning, P-Tuning and Prefix-Tuning) are not modifying the base models and their logic is coupled to the nlp task-specific classes such as PeftModelForSeq2SeqLM
> 5. Going forward, all the methods should implement the logic in the way LoRA integration is implemented by injecting/modifying the base model so that it is widely applicable to most of the models and without having to depend on the nlp task-specific classes such as PeftModelForSeq2SeqLM. This has made it quite popular among practitioners.
> 6. Give proper citations to method, code and implementation utilities
> 7. Write a few tests and example notebooks to test out the peft method and have it as ready to use artefact for end users. This has particularly helped with the adoption of PEFT.
> 
> Follow the LoRA implementation as a reference and develop the new method following it

Thanks a lot!

**Comment by GeyuanZhang** [comment]
> Hello @GeyuanZhang, Thank you for your interest in adding new methods to the repo. Please find below rough guidelines on how the library is structured, the interfaces to implement and suggestions going forward:
> 
> 1. Each parameter-efficient fine-tuning method is in a separate file in the tuners folder : [peft/src/peft/tuners at main · huggingface/peft · GitHub](https://github.com/huggingface/peft/tree/main/src/peft/tuners)
> 2. Main class if PeftModel in [peft/peft_model.py at main · huggingface/peft · GitHub](https://github.com/huggingface/peft/blob/main/src/peft/peft_model.py) with downstream nlp task specific class implementations, e.g., PeftModelForSeq2SeqLM
> 3. Each tuner has following interfaces, taking [peft/lora.py at main · huggingface/peft · GitHub](https://github.com/huggingface/peft/blob/main/src/peft/tuners/lora.py) as example:
>    A config extending PeftConfig
>    A tuner-specific class implementing the PEFT logic for the corresponding method.
> 4. Currently, only LoRA method modifies the base model in place by injecting additional layers. Prompt learning based methods (Prompt Tuning, P-Tuning and Prefix-Tuning) are not modifying the base models and their logic is coupled to the nlp task-specific classes such as PeftModelForSeq2SeqLM
> 5. Going forward, all the methods should implement the logic in the way LoRA integration is implemented by injecting/modifying the base model so that it is widely applicable to most of the models and without having to depend on the nlp task-specific classes such as PeftModelForSeq2SeqLM. This has made it quite popular among practitioners.
> 6. Give proper citations to method, code and implementation utilities
> 7. Write a few tests and example notebooks to test out the peft method and have it as ready to use artefact for end users. This has particularly helped with the adoption of PEFT.
> 
> Follow the LoRA implementation as a reference and develop the new method following it

@pacman100 Thanks a lot!
