### ISSUE TITLE
google/flan-t5-small, PrefixTuning: RuntimeError: shape is invalid for input of size

### ISSUE THREAD

**Issue by VukVukovic** [huggingface/peft#385]
When running `PrefixTuning`, with a `SEQ_2_SEQ_LM` task on `google/flan-t5-small` model from HuggingFace, I get the following error:
```
...
  File "/home/src/hac/engine.py", line 34, in _update
    outputs = model(**inputs)
  File "/home/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/.venv/lib/python3.10/site-packages/peft/peft_model.py", line 705, in forward
    past_key_values = self.get_prompt(batch_size)
  File "/home/.venv/lib/python3.10/site-packages/peft/peft_model.py", line 242, in get_prompt
    past_key_values = past_key_values.view(
RuntimeError: shape '[8, 8, 16, 6, 85]' is invalid for input of size 524288
```
For a reference, `[8, 8, ...` is `[batch_size, num_virtual_tokens, ...`.

On the other hand, `google/flan-t5-base` and `google/flan-t5-xl` worked properly in the exact same setting.

**Comment by yuqiii-wang** [comment]
Try 512-num_virtual_tokens

https://discuss.huggingface.co/t/tensor-size-error-in-peft-prefix-tuning/32264/3

**Comment by gsoykan** [comment]
I encountered a similar issue with the mT0-small model. To address this, I made some modifications to the internal implementation. Here's a brief overview of the changes:

1. **Modification in `prefix_tuning/model.py`**: 
   I adjusted the token dimension specifically for the mT0-small model. The updated `__init__` method in `prefix_tuning/model.py` now looks like this:

    ```python
    def __init__(self, config):
        super().__init__()
        self.prefix_projection = config.prefix_projection
        # Special handling for mT0-small model
        if 'mt0-small' in config.base_model_name_or_path:
            token_dim = 6 * 64  # Custom dimension for mT0-small
        else:
            token_dim = config.token_dim
    ```

2. **Adjustment in `peft_model.py`**:
   Similarly, in `peft_model.py`, I made a conditional change to the `token_dim` based on whether the model is mT0-small. The relevant code snippet is:

    ```python
    token_dim = peft_config.token_dim if 'mt0-small' not in peft_config.base_model_name_or_path else (6 * 64)
    past_key_values = past_key_values.view(
        batch_size,
        peft_config.num_virtual_tokens,
        peft_config.num_layers * 2,
        peft_config.num_attention_heads,
        token_dim // peft_config.num_attention_heads,
    )
    ```

These changes specifically tailor the token dimension to align with the requirements of the mT0-small model. So basically, the token_dim for this model should have been 384 not 512, i think that is because the MT5Attention for small model has in_features=512, out_features=384
