### ISSUE TITLE
multi-LORA

### ISSUE THREAD

**Issue by zhanghanweii** [huggingface/peft#518]
Is it possible to use multiple LORAs for synchronized forecasting? 
for example, I trained LORA for two separate tasks. When predicting, I want to load both LORA weights at the same time to perform the task of punctuation and case recovery at the same time

**Comment by Karenlyw** [comment]
> 

same question, did you find the answer?

**Comment by ZhixiuYe** [comment]
same question, did you find the answer?

**Comment by lrx1213** [comment]
same question, did you find the answer?

**Comment by damithsenanayake** [comment]
would the batching and scheduling approaches in S-LoRA https://arxiv.org/abs/2311.03285 be useful in your case ?

**Comment by BenjaminBossan** [comment]
> Is it possible to use multiple LORAs for synchronized forecasting?
for example, I trained LORA for two separate tasks. When predicting, I want to load both LORA weights at the same time to perform the task of punctuation and case recovery at the same time

This is possible. One way is to first load the first adapter as usual with `PeftModel.from_pretrained`. Next you could `merge_and_unload` the model, so that you get a model with the first adapter baked in. Now repeat the loading process, passing the merged model to `PeftModel.from_pretrained`. Optionally, you can merge and unload again after this step.

Alternatively, after loading the first adapter, you could load the next adapter using `model.add_adapter("adapter-2", config2)`, and then activate both of them using `model.base_model.set_adapter(["default, "adapter-2"])`. This is a bit of a hidden feature that we haven't documented yet, but it should work. Use this option if you don't want to merge the adapters.

> would the batching and scheduling approaches in S-LoRA https://arxiv.org/abs/2311.03285 be useful in your case ?

From my understanding, S-LoRA is especially useful in situations where you want to serve hundreds of LoRA adapters.

**Comment by yezhem** [comment]
We have implemented a synchronous training approach [multi-lora-fine-tune](https://github.com/TUDB-Labs/multi-lora-fine-tune) and the ideas for synchronous prediction and synchronous training should be similar: 
1. fuse input data into a large batch, sharing the base model during computation
2. break down the fused information into different matrices when passing through the LoRA module. This allows for calculations with different LoRA modules. 

Due to significant differences in data volume between prediction and training when passing through the LoRA module, special CUDA operators may be needed for optimization. You can refer to how [S-LoRA](https://arxiv.org/abs/2311.03285)  implements this operator.
