### ISSUE TITLE
Have model cards that contains details that config doesn't have

### ISSUE THREAD

**Issue by merveenoyan** [huggingface/peft#584]
### Feature request

It would be better if the model cards contain details that enable reproducibility in experiments, e.g. bitsandbytes quantization configurations. 

### Motivation

Configuration files don't have fine-grained details about quantization or base model (or anything PEFT could introduce except for very fundamental info). 

### Your contribution

I could submit a PR if we could discuss about it first :')

**Comment by younesbelkada** [comment]
HI @merveenoyan 
I think this is a good idea, instead of having it on the model card, what about adding a field in `PeftConfig` that store all these extra configs / attributes (e.g. `extra_config_info`) ? We just need to make sure these extra fields are serializable so that anyone can push them on the Hub.
