### ISSUE TITLE
Not getting substantial training time improvement with LORA - is this expected ?

### ISSUE THREAD

**Issue by SuchandraDatta** [huggingface/peft#664]
Hi all.

I am not getting a substantial training time improvement with LORA 
Details :
My dataset size is ~2M training samples
1. When I am fine-tuning roberta-base model ( base model has ~125M trainable parameters ) training time is roughly 30.5hrs
2. When I am fine-tuning roberta-base with LORA ( r=8, lora_alpha=8, ~2M trainable parameters ) training time is roughly 29hrs
- Batch size, number of GPUs, number of epochs is same for both 1 and 2

Are we guaranteed to observe a substantial improvement in training time when using LORA on large datasets ?
Can anyone please guide regarding this

**Comment by younesbelkada** [comment]
Hi @SuchandraDatta 
Thanks for the report, if I am not mistaken I don't think there is any signification training time improvement when using LoRA due to some computational overhead of the Lora layers. The main perk of the method is to be able to FT very large model on smaller devices and drastically reduce the GPU memory requirement when fine-tuning your model. Hope that makes sense!

**Comment by zheng5yu9** [comment]
in my case ,  ddp=deepspeed, progress=8A100, when using lora, triaing speed slow down from 2.6sample/s->0.5sample/s, is it  right?

**Comment by SuchandraDatta** [comment]
> Hi @SuchandraDatta Thanks for the report, if I am not mistaken I don't think there is any signification training time improvement when using LoRA due to some computational overhead of the Lora layers. The main perk of the method is to be able to FT very large model on smaller devices and drastically reduce the GPU memory requirement when fine-tuning your model. Hope that makes sense!

Hi thanks for this, it makes sense.
