### ISSUE TITLE
get_peft_model() changes the parameter names, with prefix: base_model.model

### ISSUE THREAD

**Issue by ndvbd** [huggingface/peft#666]
### System Info

Is there a way to prevent the function from adding the prefix to the parameter names?

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

N/A

### Expected behavior

Parameters to keep the same names, because if you do get_peft_model() once, and then you want to add another adapator, and another, you keep accruing prefixes

**Comment by younesbelkada** [comment]
Hi @ndvbd 
Thanks for the report,
from my understanding this is currently not doable by the design of the library. When using HF models we need to wrap the base model in a super class to correctly deal with model loading with accelerate for large models.
cc @BenjaminBossan @pacman100

**Comment by BenjaminBossan** [comment]
I was thinking about this issue as well. Having the added prefixes can be annoying, so I see where this is coming from.

> this is currently not doable by the design of the library. When using HF models we need to wrap the base model in a super class to correctly deal with model loading with accelerate for large models

Could you elaborate why this requires the addition of prefixes? I know that PyTorch will automatically create prefixes when a module is an attribute of another module, but I'm not sure how that relates to accelerate.

Anyway, I think it is probably (almost) impossible to get rid of prefixes entirely because of the wrapping, but I do wonder if we really need _two prefixes_, i.e. `'base_model'` and `'model'`. What is the necessity here?

Another issue we need to consider is the following: Can we change the prefixes without making all existing tuned weights backwards incompatible? If they are matched by name, we cannot rename the keys without invalidating them. Maybe there is a way to convert the names from old to new scheme, but this sounds like it could easily go wrong.
