### ISSUE TITLE
Use `peft` for RLHF

### ISSUE THREAD

**Issue by younesbelkada** [huggingface/peft#71]
# Feature request

We should leverage `trl`: https://github.com/lvwerra/trl - the recent library from Hugging Face for RLHF, to apply PPO using `peft` and LoRA

I think `peft` should just work out of the box, the first step could be trying to adapt `gpt2-sentiment.py` script: https://github.com/lvwerra/trl/blob/main/examples/sentiment/scripts/gpt2-sentiment.py to use `peft`

**Comment by BirgerMoell** [comment]
@pacman100 @younesbelkada  I could work on this if there is any interest. What would be the first steps?

**Comment by younesbelkada** [comment]
Thanks for your interest @BirgerMoell !! That would be definitely helpful 
We need to check first the compatbility of `peft` and `trl` (i.e. it might not directly work out of the box but we will need to double check), so we will most likely adapt the gpt2 script ourselves just to make sure we fix things that needs to be fixed, then you can help us maybe converting the t5 script? Let me know what do you think!
If you feel you want to take the challenge and start converting the gpt2 script feel free to do it and we'll be happy to review your Pull Request / code changes ! 🔥

**Comment by BirgerMoell** [comment]
I think it sounds like a good idea if you start out with the gpt2 script and then I can do the t5 script. I think that would be a nice way to do it and I can understand much more by following along with your work.
Btw I'm on the huggingface discord if you want to messag me my username is birger

**Comment by younesbelkada** [comment]
The PR https://github.com/lvwerra/trl/pull/163 should add `peft` support on `trl`, we may need to convert the other scripts such as t5 summarization etc as well once this PR gets merged!

**Comment by Tarak200** [comment]
```markdown
### 🐛 Bug Report: AttributeError in `DeepSpeedEngine` when accessing `base_model_prefix` for PPO training using trl

#### Description
When running PPO training with a PEFT-based reward model wrapped in DeepSpeed, an `AttributeError` occurs when trying to access `base_model_prefix` from the model. It seems that `DeepSpeedEngine` does not expose this attribute, leading to a crash.

#### Error Traceback
```
Traceback (most recent call last):
[rank6]:   File "/raid/ganesh/nithin/trl/examples/scripts/ppo/ppo.py", line 211, in <module>
[rank6]:     trainer.train()
[rank6]:   File "/raid/ganesh/nithin/trl/trl/trainer/ppo_trainer.py", line 462, in train
[rank6]:     _, score, _ = get_reward(
[rank6]:                   ^^^^^^^^^^^
[rank6]:   File "/raid/ganesh/nithin/trl/trl/trainer/utils.py", line 1179, in get_reward
[rank6]:     lm_backbone = getattr(model, model.base_model_prefix)
[rank6]:                                  ^^^^^^^^^^^^^^^^^^^^^^^
[rank6]:   File "/raid/ganesh/nithin/trl/myenv/lib/python3.12/site-packages/deepspeed/runtime/engine.py", line 519, in __getattr__
[rank6]:     raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
[rank6]: AttributeError: 'DeepSpeedEngine' object has no attribute 'base_model_prefix'
```

#### Code to Reproduce
```python

quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
    )

reward_model_path = "Qwen/Qwen2.5-Coder-3B-Instruct"

reward_model = AutoModelForSequenceClassification.from_pretrained(
    reward_model_path,
    trust_remote_code= True,
    num_labels=1,
    quantization_config=quantization_config,
)

adapter_path = "./reward_model_SC-qwen-3B-4096/final_checkpoint"
reward_model_ft = PeftModel.from_pretrained(reward_model, adapter_path)


#### Expected Behavior
- The model should correctly load as a PEFT-based reward model.
- The training should proceed without errors related to `base_model_prefix`.

#### Actual Behavior
- The script crashes when trying to access `model.base_model_prefix` since `DeepSpeedEngine` does not have this attribute.

#### Environment
- **DeepSpeed Version:** `0.16.3`
- **Transformers Version:** `4.48.3`
- **TRL Version:** `0.15.0`
- **Python Version:** `3.12`
- **Model Used:** `qwen-3B`
- **Hardware:** `8 A100s`

Would appreciate any guidance or solutions. Thanks! 
```

**Comment by BenjaminBossan** [comment]
@Tarak200 Is this the same issue as https://github.com/huggingface/trl/issues/2718? Maybe you could post your reproducer there and will be more likely to get help.
