### ISSUE TITLE
Performance degradation with HF Trainer when training LayoutLMv3

### ISSUE THREAD

**Issue by anthony2261** [huggingface/peft#765]
### System Info

peft == 0.4.0
transformers == 4.31.0
accelerate==0.21.0

Colab notebook shared below

python 3.10.6

### Who can help?

@pacman100 @sayakpaul, (and potentially @NielsRogge as I've adapted the notebook from his [examples](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LayoutLMv3/Fine_tune_LayoutLMv3_on_FUNSD_(HuggingFace_Trainer).ipynb))

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

In this [notebook](https://colab.research.google.com/drive/1ziwHwlZlODOvqkNqGOejPMMd8eXKRs5b?usp=sharing), I train `LayoutLMv3` with LoRa in two ways:
- using the HuggingFace `Trainer`
- using a manual training loop

The issue is that the HF Trainer yields far worse results (f1=0.68) than that of the manual training (f1=0.89), even when the Trainer trains for 3x more epochs than the manual training.

Note that I've adapted Sourab's training loop from the [official example](https://github.com/huggingface/peft/blob/main/examples/token_classification/peft_lora_token_cls.ipynb) for token classification with LoRa using LayoutLM (v1)

### Expected behavior

Using the HF Trainer yields similar results to the manual training loop

**Comment by anthony2261** [comment]
-

**Comment by BenjaminBossan** [comment]
So just to ensure I understand correctly, you're using LayoutLMv3 with PEFT (LoRA) and the issue is that your manual training loop works better than HF Trainer? In that case, it sounds to me like this is not a PEFT issue.

In general, it is always quite hard to get the exact same results with two different training methods. Are you very sure that the hyper-parameters are 100% identical between the two? If yes, then I would suggest opening an issue in the transformers repo with code that shows the difference, people there might be able to help you.

**Comment by anthony2261** [comment]
@BenjaminBossan I tried to get the configurations/hyperparameters of the two training methods to be as close as possible to each other (to the best of my knowledge, of course).

I'll open an issue on the transformers side, thank you!
