### ISSUE TITLE
Request for clearer handling of CUDA resources between peft and accelerate/bitsandbytes

### ISSUE THREAD

**Issue by cassianlewis** [huggingface/peft#819]
### System Info

```
peft == 0.5.0.dev0
bitsandbytes == 0.41.1
accelerate == 0.22.0.dev0
torch == 2.0.0
transformers == 4.32.0.dev0
```

### Who can help?

@younesbelkada 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

```
from peft import get_peft_model
import torch
torch.cuda.is_initialized()
```

returns `True`

This then causes issues when using accelerates `notebook_launcher`, eg:
```
def run():
    
    model = AutoModelForSeq2SeqLM.from_pretrained(
            't5-small',
            # load_in_8bit = 'True',
            # device_map = 'auto',
            cache_dir='model_cache')
    
    print(model)
    print('Testing')
```

```
notebook_launcher(run, num_processes = 2)
```

### Expected behavior

Following error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[9], line 1
----> 1 notebook_launcher(run, num_processes = 2)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/accelerate/launchers.py:123, in notebook_launcher(function, args, num_processes, mixed_precision, use_port)
    116     raise ValueError(
    117         "To launch a multi-GPU training from your notebook, the `Accelerator` should only be initialized "
    118         "inside your training function. Restart your notebook and make sure no cells initializes an "
    119         "`Accelerator`."
    120     )
    122 if torch.cuda.is_initialized():
--> 123     raise ValueError(
    124         "To launch a multi-GPU training from your notebook, you need to avoid running any instruction "
    125         "using `torch.cuda` in any cell. Restart your notebook and make sure no cells use any CUDA "
    126         "function."
    127     )
    129 # torch.distributed will expect a few environment variable to be here. We set the ones common to each
    130 # process here (the other ones will be set be the launcher).
    131 with patch_environment(
    132     world_size=num_processes, master_addr="127.0.01", master_port=use_port, mixed_precision=mixed_precision
    133 ):

ValueError: To launch a multi-GPU training from your notebook, you need to avoid running any instruction using `torch.cuda` in any cell. Restart your notebook and make sure no cells use any CUDA function.
```

I believe `peft` is calling `bitsandbytes` under the hood during imports which is initialising cuda (this doesn't happen if I uninstall `bitsandbytes`. 

Related to https://github.com/huggingface/accelerate/pull/1833

@muellerzr

**Comment by muellerzr** [comment]
This requires some fairly significant refactors in a few areas, so my recommendation is to include all imports to `peft` under the function to be called for the `notebook_launcher`. With this it should work.

If it seems desirable in the future, here is my analysis of what needs/should be changed:

- Change all `bnb` import checks to rely on their equivalent `accelerate.utils.imports` versions. `accelerate` is already a main dep, and we check it in a way that doesn't trigger `bnb` spinning up (the main issue here)
- `ia3`, `adalore`, and `lora` need to be modified somehow to have potentially a late init of `bnb`, or make it more specific to get the import so that `bnb` does not spin up. 

Sadly this is an annoying behavior with `bitsandbytes` that will spin up and spawn CUDA *always* when importing it, which leads to these headaches. cc @SunMarc @younesbelkada
