### ISSUE TITLE
Ln437 in peft_model : hub_file_exists  will cause unhandled exception when TRANSFORMERS_OFFLINE=1

### ISSUE THREAD

**Issue by gamert** [huggingface/peft#867]
### System Info

peft "0.4.0.dev0"

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

I use generate.py by https://github.com/tloen/alpaca-lora

### Expected behavior

hub_file_exists in hub_utils
    except :
        return False

or if_offline_mode_is_enabled ,return False

**Comment by BenjaminBossan** [comment]
Thanks for reporting. Yes, having an unhandled exception here is not nice. However, I think if we reach that code path, we have to raise some kind of error, since it means the weights couldn't be found locally and should not be downloaded from HF Hub. So would your expected solution just be to raise a better exception?
