### ISSUE TITLE
Attaching lora at runtime 

### ISSUE THREAD

**Issue by monksgoyal** [huggingface/peft#885]
### Feature request

So suppose for the same base model like Qwen i want to attach multiple lora layers for different tasks.
Number of tasks can be as large as 10 +.
Now if want to perform all these tasks via single A100 GPU, i dont want to load multiple models.
I want to load single base model and attach Lora weights on the fly during runtime to save memory.
I know it will increase latency but that is something i am ok with.

How to achieve this such that GPU memory is taken mostly by base model?

Any help will be appreciated.

### Motivation

Low memory environment PEFT.

### Your contribution

NA

**Comment by BenjaminBossan** [comment]
Load your first `PeftModel` as usual. It should have one LoRA adapter now. On the `PeftModel` instance, you can now call `add_adapter` to add more adapters to the same base model. With `set_adapter`, you can switch between the different adapters.

**Comment by kian98** [comment]
@BenjaminBossan  Could you please provide information on the latency of the set_adapter operation after loading multiple adapters compared to loading only one adapter?


> Load your first `PeftModel` as usual. It should have one LoRA adapter now. On the `PeftModel` instance, you can now call `add_adapter` to add more adapters to the same base model. With `set_adapter`, you can switch between the different adapters.

**Comment by BenjaminBossan** [comment]
> Could you please provide information on the latency of the set_adapter operation after loading multiple adapters compared to loading only one adapter?

Could you elaborate on what you mean? Do you mean how long it takes to call `set_adapter`? It will depend on the model, but shouldn't be too much (let us know if it is very slow for you). However, if you want to call it very frequently, e.g. because you want to change the adapter for each incoming inference call, this overhead could add up.

**Comment by kian98** [comment]
Thank you for your insight earlier. I'd like to expand on a specific scenario I'm dealing with. In my setup, a large language model operates with multiple adapters to offer API services, and the selection of the adapter is determined by the incoming request's parameters. My question revolves around the potential latency impact: Is there a significant delay in API response times when switching between adapters in this setup compared to running each adapter on a dedicated language model instance?

From my understanding, set_adapter essentially activates the chosen adapter and iterates through all active adapters during the inference process. In some preliminary tests with a dual-adapter setup, I didn't notice any substantial latency when switching between them. So, I'm leaning towards the conclusion that adapter switching per request doesn't notably impact performance. Would you agree with this assessment? Also, could you clarify what you meant by 'overhead could add up' in this scenario? Thanks again!

**Comment by BenjaminBossan** [comment]
Thanks for explaining your use case, this is roughly what I imagined.

I cannot answer for you the question if the switching of adapters will create a significant slowdown or not. It depends on several factors, e.g. how often the adapters are being switched or how large the model is (the larger the model, the more time spent on inference, the less the switching should be noticeable). At the end of the day, you have to measure the performance and decide if it's worth it for you to serve each adapter on a separate instance or use the same instance and switch.

One thing to keep in mind is that if you only serve a single adapter per instance, you can `merge_and_unload` the model, which should make it slightly smaller and slightly faster. This doesn't work if you want to dynamically switch adapters.

We are currently also working on a solution that would allow to serve multiple adapters at the same time within the same batch: #903. So if batching is a factor to you, keep an eye on that PR (it has been stalled for some time unfortunately).

Otherwise, if you are serving a large number of different adapters at the same time, solutions such as https://github.com/S-LoRA/S-LoRA could be interesting (I haven't tested it personally though).

**Comment by BenjaminBossan** [comment]
> We are currently also working on a solution that would allow to serve multiple adapters at the same time within the same batch: #903. So if batching is a factor to you, keep an eye on that PR (it has been stalled for some time unfortunately).

We merged #1558, a follow up to https://github.com/huggingface/peft/pull/903. Maybe you can take a look if it could be interesting for your use case.

**Comment by jinghanSunn** [comment]
Hi @BenjaminBossan,

Thank you very much for your detailed explanation. I have a small question regarding the difference between set_adapter and merge_and_unload when loading adapters.

I've noticed that when I load multiple adapters using set_adapter, the GPU memory usage increases only for the LoRA parameters, rather than for the base model + LoRA adapter, however, when I use merge_and_unload to load multiple adapters, the memory usage increases for both the base model and the LoRA adapters.

From this observation, I assume that using set_adapter simply changes the inference method without merging the LoRA parameters into the base model. Is that correct?

Thank you for your clarification!

**Comment by BenjaminBossan** [comment]
> From this observation, I assume that using set_adapter simply changes the inference method without merging the LoRA parameters into the base model. Is that correct?

This is correct, `set_adapter` does not perform any merging. Therefore, you'll see the small LoRA compute overhead that is expected when LoRA is not merged.
